{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "from ossapi import Ossapi\n",
    "import sqlite3\n",
    "from time import strftime, localtime\n",
    "import time\n",
    "from concurrent.futures import ThreadPoolExecutor\n",
    "import sys\n",
    "from numpy import array_split\n",
    "import pickle\n",
    "from datetime import datetime\n",
    "sys.path.insert(0, \"../\") # Required for database in different directory. \n",
    "\n",
    "OSU_CLIENT_ID = os.environ.get('OSU_CLIENT_ID')\n",
    "OSU_CLIENT_SECRET = os.environ.get('OSU_CLIENT_SECRET')\n",
    "\n",
    "api = Ossapi(OSU_CLIENT_ID, OSU_CLIENT_SECRET)\n",
    "\n",
    "with open(\"leaderboard_ids.pickle\", \"rb\") as handle:\n",
    "    leaderboard_ids = pickle.load(handle)\n",
    "leaderboard_ids = set(leaderboard_ids)\n",
    "\n",
    "top_or_recent = \"recent\"\n",
    "mode = \"std\"\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 86,
   "metadata": {},
   "outputs": [
    {
     "ename": "ValueError",
     "evalue": "api returned an error of `Specified Solo\\Score couldn't be found.` for a request to https://osu.ppy.sh/api/v2/scores/osu/1742868886",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[86], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m eggtofu \u001b[38;5;241m=\u001b[39m \u001b[43mapi\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mscore\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mosu\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m1742868886\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/osu_oracle/osu_oracle_venv/lib/python3.10/site-packages/ossapi/ossapiv2.py:211\u001b[0m, in \u001b[0;36mrequest.<locals>.decorator.<locals>.wrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    208\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m id_:\n\u001b[1;32m    209\u001b[0m         kwargs[arg_name] \u001b[38;5;241m=\u001b[39m id_\n\u001b[0;32m--> 211\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfunction\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/osu_oracle/osu_oracle_venv/lib/python3.10/site-packages/ossapi/ossapiv2.py:2376\u001b[0m, in \u001b[0;36mOssapi.score\u001b[0;34m(self, mode, score_id)\u001b[0m\n\u001b[1;32m   2356\u001b[0m \u001b[38;5;129m@request\u001b[39m(Scope\u001b[38;5;241m.\u001b[39mPUBLIC, category\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mscores\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m   2357\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mscore\u001b[39m(\u001b[38;5;28mself\u001b[39m,\n\u001b[1;32m   2358\u001b[0m     mode: GameModeT,\n\u001b[1;32m   2359\u001b[0m     score_id: \u001b[38;5;28mint\u001b[39m\n\u001b[1;32m   2360\u001b[0m ) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m Score:\n\u001b[1;32m   2361\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[1;32m   2362\u001b[0m \u001b[38;5;124;03m    Get a score.\u001b[39;00m\n\u001b[1;32m   2363\u001b[0m \n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   2374\u001b[0m \u001b[38;5;124;03m    <https://osu.ppy.sh/docs/index.html#scoresmodescore>`__ endpoint.\u001b[39;00m\n\u001b[1;32m   2375\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[0;32m-> 2376\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_get\u001b[49m\u001b[43m(\u001b[49m\u001b[43mScore\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;124;43mf\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43m/scores/\u001b[39;49m\u001b[38;5;132;43;01m{\u001b[39;49;00m\u001b[43mmode\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mvalue\u001b[49m\u001b[38;5;132;43;01m}\u001b[39;49;00m\u001b[38;5;124;43m/\u001b[39;49m\u001b[38;5;132;43;01m{\u001b[39;49;00m\u001b[43mscore_id\u001b[49m\u001b[38;5;132;43;01m}\u001b[39;49;00m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/osu_oracle/osu_oracle_venv/lib/python3.10/site-packages/ossapi/ossapiv2.py:675\u001b[0m, in \u001b[0;36mOssapi._get\u001b[0;34m(self, type_, url, params)\u001b[0m\n\u001b[1;32m    674\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_get\u001b[39m(\u001b[38;5;28mself\u001b[39m, type_, url, params\u001b[38;5;241m=\u001b[39m{}):\n\u001b[0;32m--> 675\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_request\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtype_\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mGET\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43murl\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mparams\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mparams\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/osu_oracle/osu_oracle_venv/lib/python3.10/site-packages/ossapi/ossapiv2.py:654\u001b[0m, in \u001b[0;36mOssapi._request\u001b[0;34m(self, type_, method, url, params, data)\u001b[0m\n\u001b[1;32m    651\u001b[0m     json_ \u001b[38;5;241m=\u001b[39m r\u001b[38;5;241m.\u001b[39mjson()\n\u001b[1;32m    653\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mlog\u001b[38;5;241m.\u001b[39mdebug(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mreceived json: \u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;132;01m{\u001b[39;00mjson\u001b[38;5;241m.\u001b[39mdumps(json_,\u001b[38;5;250m \u001b[39mindent\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m4\u001b[39m)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m--> 654\u001b[0m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_check_response\u001b[49m\u001b[43m(\u001b[49m\u001b[43mjson_\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mr\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43murl\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    656\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_instantiate_type(type_, json_)\n",
      "File \u001b[0;32m~/osu_oracle/osu_oracle_venv/lib/python3.10/site-packages/ossapi/ossapiv2.py:663\u001b[0m, in \u001b[0;36mOssapi._check_response\u001b[0;34m(self, json_, url)\u001b[0m\n\u001b[1;32m    658\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_check_response\u001b[39m(\u001b[38;5;28mself\u001b[39m, json_, url):\n\u001b[1;32m    659\u001b[0m     \u001b[38;5;66;03m# TODO this should just be `if \"error\" in json`, but for some reason\u001b[39;00m\n\u001b[1;32m    660\u001b[0m     \u001b[38;5;66;03m# `self.search_beatmaps` always returns an error in the response...\u001b[39;00m\n\u001b[1;32m    661\u001b[0m     \u001b[38;5;66;03m# open an issue on osu-web?\u001b[39;00m\n\u001b[1;32m    662\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mlen\u001b[39m(json_) \u001b[38;5;241m==\u001b[39m \u001b[38;5;241m1\u001b[39m \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124merror\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;129;01min\u001b[39;00m json_:\n\u001b[0;32m--> 663\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mapi returned an error of `\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mjson_[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124merror\u001b[39m\u001b[38;5;124m'\u001b[39m]\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m` for \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    664\u001b[0m             \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124ma request to \u001b[39m\u001b[38;5;132;01m{\u001b[39;00munquote(url)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m    666\u001b[0m     \u001b[38;5;66;03m# some endpoints only require authorization grant for some endpoints.\u001b[39;00m\n\u001b[1;32m    667\u001b[0m     \u001b[38;5;66;03m# e.g. normally api.match only requires client credentials grant, but for\u001b[39;00m\n\u001b[1;32m    668\u001b[0m     \u001b[38;5;66;03m# private matches like api.match(111632899), it will return this error.\u001b[39;00m\n\u001b[1;32m    669\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m json_ \u001b[38;5;241m==\u001b[39m {\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mauthentication\u001b[39m\u001b[38;5;124m\"\u001b[39m: \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mbasic\u001b[39m\u001b[38;5;124m\"\u001b[39m}:\n",
      "\u001b[0;31mValueError\u001b[0m: api returned an error of `Specified Solo\\Score couldn't be found.` for a request to https://osu.ppy.sh/api/v2/scores/osu/1742868886"
     ]
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 81,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'Insane'"
      ]
     },
     "execution_count": 81,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "eggtofu.version"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "num_done = 0\n",
    "last_time = time.time()\n",
    "\n",
    "def scrape_users(ids):\n",
    "    \"\"\"\n",
    "    Adds user data to users table and scores to scores in ../data/UserScores.db after scraping.\n",
    "    ids: list of ids to scrape\n",
    "    \"\"\"\n",
    "    global num_done\n",
    "    global last_time\n",
    "    conn = sqlite3.connect(\"../data/UserScores.db\")  \n",
    "    cursor = conn.cursor()\n",
    "    try:\n",
    "        for user_id in ids:\n",
    "            try:\n",
    "                top_scores = api.user_scores(user_id, type=\"recent\", mode=\"osu\", limit=100)\n",
    "                scores = []\n",
    "            except Exception as e:\n",
    "                print(e)\n",
    "                continue\n",
    "\n",
    "            for score in top_scores:\n",
    "                try:\n",
    "                    beatmap = getattr(score, \"beatmap\", None)\n",
    "                    beatmap_id = getattr(beatmap, \"id\", None) if beatmap else None\n",
    "                    \n",
    "                    beatmapset_id = getattr(beatmap, \"beatmapset_id\", None) if beatmap else None\n",
    "\n",
    "                    mods = getattr(score, \"mods\", None)\n",
    "                    mods = getattr(mods, \"value\", None) if mods else None\n",
    "\n",
    "                    pp = getattr(score, \"pp\", None)\n",
    "\n",
    "                    created_at = getattr(score, \"created_at\", None)\n",
    "                    created_at = (\n",
    "                        datetime.strftime(created_at, \"%Y-%m-%d %H:%M:%S\")\n",
    "                        if created_at\n",
    "                        else None\n",
    "                    )\n",
    "\n",
    "                    score = (\n",
    "                        int(user_id),\n",
    "                        beatmap_id,\n",
    "                        beatmapset_id,\n",
    "                        pp,\n",
    "                        mods,\n",
    "                        created_at,\n",
    "                    )\n",
    "                    scores.append(score)\n",
    "\n",
    "                except Exception as e:\n",
    "                    print(e)\n",
    "                    continue\n",
    "\n",
    "            try:\n",
    "                cursor.executemany(\n",
    "                    f\"\"\"\n",
    "                    INSERT INTO {top_or_recent}_scores_{mode} (user_id, beatmap_id, beatmapset_id, pp, mods, created_at)\n",
    "                    VALUES (?, ?, ?, ?, ?, ?)\n",
    "                    \"\"\",\n",
    "                    scores,\n",
    "                )\n",
    "                conn.commit()\n",
    "            except Exception as e:\n",
    "                print(e)\n",
    "                continue\n",
    "\n",
    "            num_done += 1\n",
    "            if num_done % 100 == 0:\n",
    "                print(\n",
    "                    str(num_done) + \": \" + str(time.time() - last_time),\n",
    "                    strftime(\"%H:%M:%S\", localtime(time.time())),\n",
    "                )\n",
    "                last_time = time.time()\n",
    "                \n",
    "    except Exception as e:\n",
    "        print(e)\n",
    "    finally:\n",
    "        conn.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Remaining user ids to scrape: 663332\n",
      "132667\n",
      "132667\n",
      "132666\n",
      "132666\n",
      "132666\n",
      "api returned an error of `None` for a request to https://osu.ppy.sh/api/v2/users/19283604/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `None` for a request to https://osu.ppy.sh/api/v2/users/10054109/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `None` for a request to https://osu.ppy.sh/api/v2/users/7521530/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `None` for a request to https://osu.ppy.sh/api/v2/users/15910145/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `None` for a request to https://osu.ppy.sh/api/v2/users/12151369/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `None` for a request to https://osu.ppy.sh/api/v2/users/10485990/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `None` for a request to https://osu.ppy.sh/api/v2/users/257/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `None` for a request to https://osu.ppy.sh/api/v2/users/14680369/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `None` for a request to https://osu.ppy.sh/api/v2/users/12151573/scores/recent?mode=osu&limit=100\n",
      "673: 7.643176078796387 18:37:29\n",
      "api returned an error of `None` for a request to https://osu.ppy.sh/api/v2/users/6292007/scores/recent?mode=osu&limit=100\n",
      "707: 2.2301619052886963 18:37:32\n",
      "api returned an error of `None` for a request to https://osu.ppy.sh/api/v2/users/8798014/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `None` for a request to https://osu.ppy.sh/api/v2/users/20104537/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `None` for a request to https://osu.ppy.sh/api/v2/users/15910280/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `None` for a request to https://osu.ppy.sh/api/v2/users/13813134/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `None` for a request to https://osu.ppy.sh/api/v2/users/19283856/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/2506715/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/11716016/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/23478234/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/1230260/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/10895326/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/15910326/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/18007479/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/12992482/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/8798180/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/13813177/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/8798181/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/15910331/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/409574/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/18007484/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/31866853/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/20104645/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/4603880/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/11716039/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/15089641/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/1230280/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/17186793/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/28493256/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/6701047/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/5424586/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/15089655/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/11716047/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/2506745/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/7521746/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/25575419/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/11716064/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/4603900/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/32687584/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/10895357/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/18007531/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/12992510/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/9618924/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/2506751/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/20104692/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/12992513/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/10895367/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/7521781/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/29769735/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/11716091/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/6701066/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/11716096/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/19283979/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/15910401/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/2506765/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/22201858/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/19283992/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/24299011/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/4603929/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/22201861/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/21381148/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/5424648/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/8798237/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/9618952/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/19284001/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/7521804/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/4603941/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/11716111/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/17186853/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/7521814/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/6701095/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/20104726/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/6701104/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/25575472/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/13813273/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/19284016/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/9618973/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/4603961/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/24299037/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/5424671/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/10895422/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/13813279/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/2506816/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/3327529/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/12992576/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/3327530/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/21381188/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/9618985/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/12992586/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/9618992/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/10895434/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/22201908/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/25575503/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/1230389/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/19284048/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/5424700/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/8798287/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/28493375/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/6701144/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/7521856/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/12992600/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/20104771/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/2506845/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/9619022/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/29769824/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/5424725/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/6701155/scores/recent?mode=osu&limit=100\n",
      "777: 8.976811408996582 18:37:41\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/15910488/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/23478371/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/16345912/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/15910494/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/21381219/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/7957309/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/11716191/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/2506854/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/5860161/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/12992612/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/20104807/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/12151622/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/29769834/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/15910504/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/16345927/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/2506859/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/22201961/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/7957321/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/23478381/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/20104811/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/7957326/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/6701166/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/30590578/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/14248784/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/409711/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/5424756/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/10054483/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/23478386/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/7521910/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/26831699/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/21381242/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/20104822/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/12151637/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/15089797/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/15910522/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/18443092/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/12992648/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/31026004/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/15910528/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/8798353/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/9619075/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/20540248/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/409747/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/1665881/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/3327626/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/8798358/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/16345954/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/7521934/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/6701207/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/3763044/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/3327632/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/8798359/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/35220327/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/20104852/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/19284120/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/3763051/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/13813400/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/15089817/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/14248816/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/9619097/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/19284121/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/1665910/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/15910554/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/6701216/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/22637435/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/17186976/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/7957373/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/15910555/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/10895521/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/10054534/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/26396315/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/12992676/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/16345992/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/7521951/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/17186982/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/22202015/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/27672743/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/16345993/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/9619112/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/19284141/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/7957385/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/20104873/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/8798383/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/26396328/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/10895541/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/18007730/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/3763088/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/19284149/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/2506937/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/22202034/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/14248858/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/10054560/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/9619126/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/33964219/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/13813431/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/14248866/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/25575624/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/9619129/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/24734636/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/10895562/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/7521991/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/5860269/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/18007759/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/31026095/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/17187018/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/9619152/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/3763121/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/15089869/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/34784975/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/14248889/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/15089871/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/5424850/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/3763132/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/8798419/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/12151747/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/20104916/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/17187030/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/16346052/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/7522005/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/6701274/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/18007762/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/18443210/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/21381339/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/3327700/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/24734669/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/7522008/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/3763150/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/12992733/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/15910617/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/31026126/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/12992735/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/18007771/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `None` for a request to https://osu.ppy.sh/api/v2/users/3763182/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `None` for a request to https://osu.ppy.sh/api/v2/users/12151808/scores/recent?mode=osu&limit=100\n",
      "851: 6.394889831542969 18:37:47\n",
      "api returned an error of `None` for a request to https://osu.ppy.sh/api/v2/users/10486389/scores/recent?mode=osu&limit=100\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[7], line 18\u001b[0m\n\u001b[1;32m     15\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m user_ids \u001b[38;5;129;01min\u001b[39;00m partitioned_user_ids:\n\u001b[1;32m     16\u001b[0m     \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;28mlen\u001b[39m(user_ids))\n\u001b[0;32m---> 18\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m ThreadPoolExecutor(max_workers\u001b[38;5;241m=\u001b[39mnum_partitions) \u001b[38;5;28;01mas\u001b[39;00m executor:\n\u001b[1;32m     19\u001b[0m     \u001b[38;5;28;01mfor\u001b[39;00m user_ids \u001b[38;5;129;01min\u001b[39;00m partitioned_user_ids:\n\u001b[1;32m     20\u001b[0m         executor\u001b[38;5;241m.\u001b[39msubmit(scrape_users, user_ids)\n",
      "File \u001b[0;32m/usr/lib/python3.10/concurrent/futures/_base.py:649\u001b[0m, in \u001b[0;36mExecutor.__exit__\u001b[0;34m(self, exc_type, exc_val, exc_tb)\u001b[0m\n\u001b[1;32m    648\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__exit__\u001b[39m(\u001b[38;5;28mself\u001b[39m, exc_type, exc_val, exc_tb):\n\u001b[0;32m--> 649\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mshutdown\u001b[49m\u001b[43m(\u001b[49m\u001b[43mwait\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m)\u001b[49m\n\u001b[1;32m    650\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mFalse\u001b[39;00m\n",
      "File \u001b[0;32m/usr/lib/python3.10/concurrent/futures/thread.py:235\u001b[0m, in \u001b[0;36mThreadPoolExecutor.shutdown\u001b[0;34m(self, wait, cancel_futures)\u001b[0m\n\u001b[1;32m    233\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m wait:\n\u001b[1;32m    234\u001b[0m     \u001b[38;5;28;01mfor\u001b[39;00m t \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_threads:\n\u001b[0;32m--> 235\u001b[0m         \u001b[43mt\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mjoin\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/usr/lib/python3.10/threading.py:1096\u001b[0m, in \u001b[0;36mThread.join\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m   1093\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mRuntimeError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mcannot join current thread\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m   1095\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m timeout \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m-> 1096\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_wait_for_tstate_lock\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   1097\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m   1098\u001b[0m     \u001b[38;5;66;03m# the behavior of a negative timeout isn't documented, but\u001b[39;00m\n\u001b[1;32m   1099\u001b[0m     \u001b[38;5;66;03m# historically .join(timeout=x) for x<0 has acted as if timeout=0\u001b[39;00m\n\u001b[1;32m   1100\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_wait_for_tstate_lock(timeout\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mmax\u001b[39m(timeout, \u001b[38;5;241m0\u001b[39m))\n",
      "File \u001b[0;32m/usr/lib/python3.10/threading.py:1116\u001b[0m, in \u001b[0;36mThread._wait_for_tstate_lock\u001b[0;34m(self, block, timeout)\u001b[0m\n\u001b[1;32m   1113\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m\n\u001b[1;32m   1115\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m-> 1116\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[43mlock\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43macquire\u001b[49m\u001b[43m(\u001b[49m\u001b[43mblock\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[43m)\u001b[49m:\n\u001b[1;32m   1117\u001b[0m         lock\u001b[38;5;241m.\u001b[39mrelease()\n\u001b[1;32m   1118\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_stop()\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "api returned an error of `None` for a request to https://osu.ppy.sh/api/v2/users/2098078/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `None` for a request to https://osu.ppy.sh/api/v2/users/27264018/scores/recent?mode=osu&limit=100\n",
      "1287: 3.3128273487091064 18:38:02\n",
      "1358: 2.6137425899505615 18:38:04\n",
      "api returned an error of `None` for a request to https://osu.ppy.sh/api/v2/users/13813650/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `None` for a request to https://osu.ppy.sh/api/v2/users/10054850/scores/recent?mode=osu&limit=100\n",
      "api returned an error of `None` for a request to https://osu.ppy.sh/api/v2/users/5860569/scores/recent?mode=osu&limit=100\n"
     ]
    }
   ],
   "source": [
    "conn = sqlite3.connect('../data/UserScores.db')\n",
    "cursor = conn.cursor()\n",
    "\n",
    "\n",
    "completed_user_ids = cursor.execute(f\"SELECT DISTINCT user_id FROM {top_or_recent}_scores_{mode}\").fetchall()\n",
    "completed_user_ids = set([x[0] for x in completed_user_ids])\n",
    "conn.close()\n",
    "\n",
    "remaining_ids = list(leaderboard_ids - completed_user_ids)\n",
    "print(f\"Remaining user ids to scrape: {len(remaining_ids)}\")\n",
    "\n",
    "num_partitions = 5\n",
    "partitioned_user_ids = array_split(remaining_ids, num_partitions)\n",
    "\n",
    "for user_ids in partitioned_user_ids:\n",
    "    print(len(user_ids))\n",
    "\n",
    "with ThreadPoolExecutor(max_workers=num_partitions) as executor:\n",
    "    for user_ids in partitioned_user_ids:\n",
    "        executor.submit(scrape_users, user_ids)\n",
    "        \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "conn.close()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "CREATE TABLE IF NOT EXISTS top_scores_std (\n",
    "    user_id INTEGER,\n",
    "    beatmap_id INTEGER,\n",
    "    beatmapset_id INTEGER,\n",
    "    pp INTEGER,\n",
    "    mods INTEGER,\n",
    "    created_at TEXT\n",
    ");"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "osu_oracle_venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
